### ISSUE TITLE
undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'

### ISSUE THREAD

**Issue by duanwolf** [moritz-wundke/Boost-for-Android#197]
I download the latest code and build with NDK19.2.5345600。I link filesystem static lib and system static lib, but this problem occurs.

cmake code:

add_library(BOOST_FILE_SYSTEM_LIBS STATIC IMPORTED jniLibs/libboost_filesystem-clang-darwin-mt-a64-1_73.a)

add_library(BOOST_SYSTEM_LIBS STATIC IMPORTED jniLibs/libboost_system-clang-darwin-mt-a64-1_73.a)

target_link_libraries( # Specifies the target library.
                       native-lib

                       # Links the target library to the log library
                       # included in the NDK.
                       ${log-lib}
                        ${BOOST_FILE_SYSTEM_LIBS}
                        ${BOOST_SYSTEM_LIBS})

using function: 
boost::filesystem::exists(PATH_TO_FILE)

Build Problem:
CMakeFiles/native-lib.dir/native-lib.cpp.o: In function `boost::filesystem::exists(boost::filesystem::path const&)':
/Users/duanbiwei/AndroidStudioProjects/BoostAsioApp/app/src/main/cpp/include/boost/filesystem/operations.hpp:159: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
